services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j-standalone
    ports:
      - "7474:7474" # Navigateur Neo4j
      - "7687:7687" # Protocole Bolt
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./conf:/var/lib/neo4j/conf
      - ./import:/var/lib/neo4j/import
      - ./plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/zied_password # Définissez le mot de passe souhaité
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes # Requis pour l'édition Entreprise
    restart: always # Politique de redémarrage du conteneur
